// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.19.4
// source: passenger.proto

package passenger

import (
	grpc "google.golang.org/grpc"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const ()

// PassengerServiceClient is the client API for PassengerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PassengerServiceClient interface {
}

type passengerServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPassengerServiceClient(cc grpc.ClientConnInterface) PassengerServiceClient {
	return &passengerServiceClient{cc}
}

// PassengerServiceServer is the server API for PassengerService service.
// All implementations must embed UnimplementedPassengerServiceServer
// for forward compatibility
type PassengerServiceServer interface {
	mustEmbedUnimplementedPassengerServiceServer()
}

// UnimplementedPassengerServiceServer must be embedded to have forward compatible implementations.
type UnimplementedPassengerServiceServer struct {
}

func (UnimplementedPassengerServiceServer) mustEmbedUnimplementedPassengerServiceServer() {}

// UnsafePassengerServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PassengerServiceServer will
// result in compilation errors.
type UnsafePassengerServiceServer interface {
	mustEmbedUnimplementedPassengerServiceServer()
}

func RegisterPassengerServiceServer(s grpc.ServiceRegistrar, srv PassengerServiceServer) {
	s.RegisterService(&PassengerService_ServiceDesc, srv)
}

// PassengerService_ServiceDesc is the grpc.ServiceDesc for PassengerService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PassengerService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "grpc_gen.passenger.PassengerService",
	HandlerType: (*PassengerServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams:     []grpc.StreamDesc{},
	Metadata:    "passenger.proto",
}
