// Code generated by go-swagger; DO NOT EDIT.

// Package restapi Swagger Example API
//
//  This is a sample server celler server.
//  Terms Of Service:
//    http://swagger.io/terms/
//  Schemes:
//    http
//  Host: localhost:9003
//  BasePath: /docs
//  Version: 1.0
//  License: Apache 2.0 http://www.apache.org/licenses/LICENSE-2.0.html
//  Contact: API Support<support@swagger.io> http://www.swagger.io/support
//
//  Consumes:
//    - application/json
//
//  Produces:
//    - application/json
//
// swagger:meta
package restapi
