// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.29.0
// 	protoc        v3.19.4
// source: factory.proto

package factory

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FactoryRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *FactoryRequest) Reset() {
	*x = FactoryRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_factory_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FactoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FactoryRequest) ProtoMessage() {}

func (x *FactoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_factory_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FactoryRequest.ProtoReflect.Descriptor instead.
func (*FactoryRequest) Descriptor() ([]byte, []int) {
	return file_factory_proto_rawDescGZIP(), []int{0}
}

type FactoryResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *FactoryResponse) Reset() {
	*x = FactoryResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_factory_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FactoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FactoryResponse) ProtoMessage() {}

func (x *FactoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_factory_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FactoryResponse.ProtoReflect.Descriptor instead.
func (*FactoryResponse) Descriptor() ([]byte, []int) {
	return file_factory_proto_rawDescGZIP(), []int{1}
}

type Factory struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Factory) Reset() {
	*x = Factory{}
	if protoimpl.UnsafeEnabled {
		mi := &file_factory_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Factory) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Factory) ProtoMessage() {}

func (x *Factory) ProtoReflect() protoreflect.Message {
	mi := &file_factory_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Factory.ProtoReflect.Descriptor instead.
func (*Factory) Descriptor() ([]byte, []int) {
	return file_factory_proto_rawDescGZIP(), []int{2}
}

var File_factory_proto protoreflect.FileDescriptor

var file_factory_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x66, 0x61, 0x63, 0x74, 0x6f, 0x72, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x10, 0x67, 0x72, 0x70, 0x63, 0x5f, 0x67, 0x65, 0x6e, 0x2e, 0x66, 0x61, 0x63, 0x74, 0x6f, 0x72,
	0x79, 0x22, 0x10, 0x0a, 0x0e, 0x46, 0x61, 0x63, 0x74, 0x6f, 0x72, 0x79, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x22, 0x11, 0x0a, 0x0f, 0x46, 0x61, 0x63, 0x74, 0x6f, 0x72, 0x79, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x09, 0x0a, 0x07, 0x46, 0x61, 0x63, 0x74, 0x6f, 0x72,
	0x79, 0x32, 0x62, 0x0a, 0x0e, 0x46, 0x61, 0x63, 0x74, 0x6f, 0x72, 0x79, 0x53, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x12, 0x50, 0x0a, 0x09, 0x52, 0x65, 0x70, 0x6c, 0x65, 0x6e, 0x69, 0x73, 0x68,
	0x12, 0x20, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x5f, 0x67, 0x65, 0x6e, 0x2e, 0x66, 0x61, 0x63, 0x74,
	0x6f, 0x72, 0x79, 0x2e, 0x46, 0x61, 0x63, 0x74, 0x6f, 0x72, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x21, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x5f, 0x67, 0x65, 0x6e, 0x2e, 0x66, 0x61,
	0x63, 0x74, 0x6f, 0x72, 0x79, 0x2e, 0x46, 0x61, 0x63, 0x74, 0x6f, 0x72, 0x79, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x12, 0x5a, 0x10, 0x67, 0x72, 0x70, 0x63, 0x5f, 0x67, 0x65,
	0x6e, 0x2f, 0x66, 0x61, 0x63, 0x74, 0x6f, 0x72, 0x79, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_factory_proto_rawDescOnce sync.Once
	file_factory_proto_rawDescData = file_factory_proto_rawDesc
)

func file_factory_proto_rawDescGZIP() []byte {
	file_factory_proto_rawDescOnce.Do(func() {
		file_factory_proto_rawDescData = protoimpl.X.CompressGZIP(file_factory_proto_rawDescData)
	})
	return file_factory_proto_rawDescData
}

var file_factory_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_factory_proto_goTypes = []interface{}{
	(*FactoryRequest)(nil),  // 0: grpc_gen.factory.FactoryRequest
	(*FactoryResponse)(nil), // 1: grpc_gen.factory.FactoryResponse
	(*Factory)(nil),         // 2: grpc_gen.factory.Factory
}
var file_factory_proto_depIdxs = []int32{
	0, // 0: grpc_gen.factory.FactoryService.Replenish:input_type -> grpc_gen.factory.FactoryRequest
	1, // 1: grpc_gen.factory.FactoryService.Replenish:output_type -> grpc_gen.factory.FactoryResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_factory_proto_init() }
func file_factory_proto_init() {
	if File_factory_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_factory_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FactoryRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_factory_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FactoryResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_factory_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Factory); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_factory_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_factory_proto_goTypes,
		DependencyIndexes: file_factory_proto_depIdxs,
		MessageInfos:      file_factory_proto_msgTypes,
	}.Build()
	File_factory_proto = out.File
	file_factory_proto_rawDesc = nil
	file_factory_proto_goTypes = nil
	file_factory_proto_depIdxs = nil
}
