// Code generated by go-swagger; DO NOT EDIT.

package platform

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"buyfree/models"
)

// PostPtRegisterOKCode is the HTTP code returned for type PostPtRegisterOK
const PostPtRegisterOKCode int = 200

/*PostPtRegisterOK OK

swagger:response postPtRegisterOK
*/
type PostPtRegisterOK struct {

	/*
	  In: Body
	*/
	Payload *models.ResponseLoginResponse `json:"body,omitempty"`
}

// NewPostPtRegisterOK creates PostPtRegisterOK with default headers values
func NewPostPtRegisterOK() *PostPtRegisterOK {

	return &PostPtRegisterOK{}
}

// WithPayload adds the payload to the post pt register o k response
func (o *PostPtRegisterOK) WithPayload(payload *models.ResponseLoginResponse) *PostPtRegisterOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post pt register o k response
func (o *PostPtRegisterOK) SetPayload(payload *models.ResponseLoginResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostPtRegisterOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// PostPtRegisterInternalServerErrorCode is the HTTP code returned for type PostPtRegisterInternalServerError
const PostPtRegisterInternalServerErrorCode int = 500

/*PostPtRegisterInternalServerError Internal Server Error

swagger:response postPtRegisterInternalServerError
*/
type PostPtRegisterInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.ResponseLoginResponse `json:"body,omitempty"`
}

// NewPostPtRegisterInternalServerError creates PostPtRegisterInternalServerError with default headers values
func NewPostPtRegisterInternalServerError() *PostPtRegisterInternalServerError {

	return &PostPtRegisterInternalServerError{}
}

// WithPayload adds the payload to the post pt register internal server error response
func (o *PostPtRegisterInternalServerError) WithPayload(payload *models.ResponseLoginResponse) *PostPtRegisterInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post pt register internal server error response
func (o *PostPtRegisterInternalServerError) SetPayload(payload *models.ResponseLoginResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostPtRegisterInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
