mysql:
  dsn: "buyfree:bf123@tcp(localhost:3306)/bf?charset=utf8&parseTime=true&loc=Local"
redis:
  addr: "127.0.0.1:6379"
  password: ""
  DB: "10"
postgresql:
  dsn: "host=localhost port=5432 user=bf dbname=bfdb password=bf123  sslmode=disable  TimeZone=Asia/Shanghai"
qiniu:
  ak: "krCw1c0mo4uyEbHNArbXQR6xpdz6QLamc99iAu_-"
  sk: "XHY438HM9qjh3c1uIOVmzdO-bjlLTSYUZzKEY7_4"
  bk: "bfcloud"
weixinapp:
  appid: "wxd776834423fadf04"
  appsecret: "00a3239022c4146ec4c3209792539c0b"
shorten:
  appid: "urveqjgajrithmkd"
  appsecret: "SEl2aHp5UTkySkFQWW5RdmJwNGRiZz09"