mysql:
  dsn: "buyfree:bf123@tcp(localhost:3306)/bf?charset=utf8&parseTime=true&loc=Local"
redis:
  addr: "127.0.0.1:6379"
  password: ""
  DB: "10"
postgresql:
  dsn: "host=localhost port=5432 user=bf dbname=bfdb password=bf123  sslmode=disable  TimeZone=Asia/Shanghai"