mysql:
  dsn: "buyfree:bf123@tcp(localhost:3306)/bf?charset=utf8&parseTime=true&loc=Local"
redis:
  addr: "redis:6379"
#  addr: "localhost:6379"
  password: ""
  DB: "10"
postgresql:
# dsn: "host=localhost port=5432 user=bf dbname=bfdb password=bf123  sslmode=disable  TimeZone=Asia/Shanghai"
 dsn: "host=postgres port=5432 user=bf dbname=bfdb password=bf123  sslmode=disable  TimeZone=Asia/Shanghai"
#   dsn: "host=localhost port=5432 user=root dbname=root password=nyarlak  sslmode=disable  TimeZone=Asia/Shanghai"
qiniu:
  ak: "krCw1c0mo4uyEbHNArbXQR6xpdz6QLamc99iAu_-"
  sk: "XHY438HM9qjh3c1uIOVmzdO-bjlLTSYUZzKEY7_4"
  bk: "bfcloud"
weixinapp:
  appid: "wxd776834423fadf04"
  appsecret: "00a3239022c4146ec4c3209792539c0b"
shorten:
  appid: "urveqjgajrithmkd"
  appsecret: "SEl2aHp5UTkySkFQWW5RdmJwNGRiZz09"

minio:
  endpoint: "minio.shoggothy.xyz"
  accessKeyID: "DTjXHMhbaC10VPeX"
  secreatAccessKey: "tuJuLo4qI9f8D9JGFOgosRL4GEe7qvK1"
  secure:
minio_user:
  dsm:
    accessKeyID: "atP1p0fin9cHiHZ9"
    secreatAccessKey: "8Aojc9Ss8Q62eNdQkhTPBNwSlhKW9iau"
    public_prefix: "minio.shoggothy.xyz:/buyfree/l"
