// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ResponseLoginResponse response login response
//
// swagger:model response.LoginResponse
type ResponseLoginResponse struct {

	// code
	Code int64 `json:"code,omitempty"`

	// jwt
	Jwt string `json:"jwt,omitempty"`

	// msg
	Msg string `json:"msg,omitempty"`

	// user ID
	UserID int64 `json:"userID,omitempty"`
}

// Validate validates this response login response
func (m *ResponseLoginResponse) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this response login response based on context it is used
func (m *ResponseLoginResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ResponseLoginResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ResponseLoginResponse) UnmarshalBinary(b []byte) error {
	var res ResponseLoginResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
